export const browserCoreExamples = [
  "opencraft browser status",
  "opencraft browser start",
  "opencraft browser stop",
  "opencraft browser tabs",
  "opencraft browser open https://example.com",
  "opencraft browser focus abcd1234",
  "opencraft browser close abcd1234",
  "opencraft browser screenshot",
  "opencraft browser screenshot --full-page",
  "opencraft browser screenshot --ref 12",
  "opencraft browser snapshot",
  "opencraft browser snapshot --format aria --limit 200",
  "opencraft browser snapshot --efficient",
  "opencraft browser snapshot --labels",
];

export const browserActionExamples = [
  "opencraft browser navigate https://example.com",
  "opencraft browser resize 1280 720",
  "opencraft browser click 12 --double",
  'opencraft browser type 23 "hello" --submit',
  "opencraft browser press Enter",
  "opencraft browser hover 44",
  "opencraft browser drag 10 11",
  "opencraft browser select 9 OptionA OptionB",
  "opencraft browser upload /tmp/opencraft/uploads/file.pdf",
  'opencraft browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opencraft browser dialog --accept",
  'opencraft browser wait --text "Done"',
  "opencraft browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opencraft browser console --level error",
  "opencraft browser pdf",
];
