#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${OPENCRAFT_INSTALL_E2E_IMAGE:-${CLAWDBOT_INSTALL_E2E_IMAGE:-opencraft-install-e2e:local}}"
INSTALL_URL="${OPENCRAFT_INSTALL_URL:-${CLAWDBOT_INSTALL_URL:-https://opencraft.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
OPENCRAFT_E2E_MODELS="${OPENCRAFT_E2E_MODELS:-${CLAWDBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e OPENCRAFT_INSTALL_URL="$INSTALL_URL" \
  -e OPENCRAFT_INSTALL_TAG="${OPENCRAFT_INSTALL_TAG:-${CLAWDBOT_INSTALL_TAG:-latest}}" \
  -e OPENCRAFT_E2E_MODELS="$OPENCRAFT_E2E_MODELS" \
  -e OPENCRAFT_INSTALL_E2E_PREVIOUS="${OPENCRAFT_INSTALL_E2E_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e OPENCRAFT_INSTALL_E2E_SKIP_PREVIOUS="${OPENCRAFT_INSTALL_E2E_SKIP_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
